apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: demo-rd-restore
  namespace: demo
spec:
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: restore-rd
  rules:
  - snapshots: [latest]
