apiVersion: ops.kubedb.com/v1alpha1
kind: PostgresOpsRequest
metadata:
  name: pg-upgrade-major-standalone
  namespace: demo
spec:
  databaseRef:
    name: pg-standalone
  type: Upgrade
  upgrade:
    targetVersion: "8.0.27"